<a href="https://colab.research.google.com/github/anjali88/Basic-ML-/blob/master/Pushpanjali_Banik_Scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Excercise 1
#Import statements
#import scikit learn libraries when the are required to understand which specifc libraries are required
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np

#load classification dataset
class_data = load_breast_cancer()
class_X = pd.DataFrame(class_data.data, columns = class_data.feature_names)
class_y = class_data.target

#check the data has loaded successfully
print(class_X.shape)
print(class_y.shape)


(569, 30)
(569,)


In [3]:
#load the regression dataset
boston = load_boston()
boston_X = pd.DataFrame(boston.data, columns = boston.feature_names)
boston_y = boston.target

##check the data has loaded successfully
print(boston_X.shape)
print(boston_y.shape)

(506, 13)
(506,)


In [6]:
#Excercise 2 - Rescaling and Standardizing Data
# Rescaling using MinMaxScaler, which converts data to a specified range, usually (0,1) or (-1,1)
# many machine learning algorithms assume data is on the same scale
#import minmaxscaler
from sklearn.preprocessing import MinMaxScaler
#create feature - use one feature but may pass all the features to rescaler
feature = class_X['texture error']
#print feature prior to rescaling
print("Features prior to rescaling:\n")
print(feature[0:8])
#print the shape
print("\nFeature shape prior to reshaping:")
print(feature.shape)


Features prior to rescaling:

0    0.9053
1    0.7339
2    0.7869
3    1.1560
4    0.7813
5    0.8902
6    0.7732
7    1.3770
Name: texture error, dtype: float64

Feature shape prior to reshaping:
(569,)


In [7]:
# we used a pandas column, so data data has wrong shape for the function
# we need a 2D tuple
#reshape the data
feature = feature.values.reshape(-1,1)

# notice we now have a (samples,feature) tuple not just a (samples,) tuple
print("\nFeature shape after reshaping:")
feature.shape


Feature shape after reshaping:


(569, 1)

In [8]:
#instantiate the scaler and pass in the range we want our value to be scaled within
minmax_scale = MinMaxScaler(feature_range=(0,1))
#Scale the feature - note the fit transform function, in the next example we will separate these steps
scaled_feature = minmax_scale.fit_transform(feature)
#view feautures we have rescaled
print("Features after  rescaling:\n")
scaled_feature[0:8]

Features after  rescaling:



array([[0.12046941],
       [0.08258929],
       [0.09430251],
       [0.17587518],
       [0.09306489],
       [0.11713225],
       [0.09127475],
       [0.22471711]])

In [9]:
#standardising rescale features so that they are normally distributed. with a mean of 0 and std. deviation of 1
#import appropriate library
from sklearn.preprocessing import StandardScaler

#transform all features in dataset, look at it before transformation
mean_std = pd.DataFrame(data={'mean':class_X.mean(), 'std':class_X.std()})

#call dataframe
mean_std[0:8]

mean         std
mean radius           14.127292    3.524049
mean texture          19.289649    4.301036
mean perimeter        91.969033   24.298981
mean area            654.889104  351.914129
mean smoothness        0.096360    0.014064
mean compactness       0.104341    0.052813
mean concavity         0.088799    0.079720
mean concave points    0.048919    0.038803

In [10]:
#create scaler
scaler = StandardScaler()

#fit the scaler - this calculates the min and max values of the dates
scaler.fit(class_X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
# transform the data using the fitted scaler - this applies the transform using the fit
standardized = scaler.transform(class_X)
# this shows the features transformed - note that this returns an array not a dataframe
standardized[0:8]

array([[ 1.09706398e+00, -2.07333501e+00,  1.26993369e+00,
         9.84374905e-01,  1.56846633e+00,  3.28351467e+00,
         2.65287398e+00,  2.53247522e+00,  2.21751501e+00,
         2.25574689e+00,  2.48973393e+00, -5.65265059e-01,
         2.83303087e+00,  2.48757756e+00, -2.14001647e-01,
         1.31686157e+00,  7.24026158e-01,  6.60819941e-01,
         1.14875667e+00,  9.07083081e-01,  1.88668963e+00,
        -1.35929347e+00,  2.30360062e+00,  2.00123749e+00,
         1.30768627e+00,  2.61666502e+00,  2.10952635e+00,
         2.29607613e+00,  2.75062224e+00,  1.93701461e+00],
       [ 1.82982061e+00, -3.53632408e-01,  1.68595471e+00,
         1.90870825e+00, -8.26962447e-01, -4.87071673e-01,
        -2.38458552e-02,  5.48144156e-01,  1.39236330e-03,
        -8.68652457e-01,  4.99254601e-01, -8.76243603e-01,
         2.63326966e-01,  7.42401948e-01, -6.05350847e-01,
        -6.92926270e-01, -4.40780058e-01,  2.60162067e-01,
        -8.05450380e-01, -9.94437403e-02,  1.80592744e+

In [12]:
#have another look at the transformed data
mean_std_transformed = pd.DataFrame(data={'mean':standardized.mean(), 'std':standardized.std()}, index=class_X.columns)

# call the dataframe
mean_std_transformed[0:8]

mean  std
mean radius         -6.118909e-16  1.0
mean texture        -6.118909e-16  1.0
mean perimeter      -6.118909e-16  1.0
mean area           -6.118909e-16  1.0
mean smoothness     -6.118909e-16  1.0
mean compactness    -6.118909e-16  1.0
mean concavity      -6.118909e-16  1.0
mean concave points -6.118909e-16  1.0

In [13]:
#Excercise 2 - Rescaling and Standardization
load_boston()

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate p

In [14]:
Class1 = load_boston()
Class1_X = pd.DataFrame(Class1.data, columns = Class1.feature_names) #features
Class1_y = Class1.target # labels
print(Class1_X.shape)
print(Class1_y.shape) #  check if data loaded successfully

# FEATURE RESCALING
from sklearn.preprocessing import MinMaxScaler # import required library
#create feature - use one feature but may pass all the features to rescaler
F1 = Class1_X['TAX']

#print feature prior to rescaling
print("Features prior to rescaling:\n")
print(F1[0:10])

#print the shape
print("\nFeature shape prior to reshaping:")
print(F1.shape)
#Reshape the data into 2D tuple for the function
F1 = F1.values.reshape(-1,1)
print("\nFeature shape after reshaping: ")
print(F1.shape)
F1[0:10]

# instantiate the scaler and pass the feature range 
minmax_scale = MinMaxScaler(feature_range=(0, 1))
#Scale the feature - note the fit transform function, in the next example we will separate these steps
scaled_F1 = minmax_scale.fit_transform(F1)
#view feautures we have rescaled
print("Features after  rescaling:\n")
scaled_F1[0:10]

#STANDARDISING - using Standardscaler
#standardise the features to be normally distributed. with a mean of 0 and std. deviation of 1
from sklearn.preprocessing import StandardScaler # import appropriate library
mean_std = pd.DataFrame(data={'mean':Class1_X.mean(), 'std':Class1_X.std()}) # transform all the features in the dataset
mean_std[0:10] # call the dataframe
print()
scaler = StandardScaler() #create the standard scaler
scaler.fit(Class1_X) #fit the scaler - this calculates the min and max values of the dates
standardized1 = scaler.transform(Class1_X) # transform the data using the fitted scaler - this applies the transform using the fit
standardized1[0:8]# this shows the features transformed - note that this returns an array not a dataframe
mean_std_transformed = pd.DataFrame(data={'mean':standardized1.mean(), 'std':standardized1.std()}, index=Class1_X.columns) #have another look at the transformed data
mean_std_transformed[0:10] # call the dataframe

(506, 13)
(506,)
Features prior to rescaling:

0    296.0
1    242.0
2    242.0
3    222.0
4    222.0
5    222.0
6    311.0
7    311.0
8    311.0
9    311.0
Name: TAX, dtype: float64

Feature shape prior to reshaping:
(506,)

Feature shape after reshaping: 
(506, 1)
Features after  rescaling:




mean  std
CRIM  -1.114746e-15  1.0
ZN    -1.114746e-15  1.0
INDUS -1.114746e-15  1.0
CHAS  -1.114746e-15  1.0
NOX   -1.114746e-15  1.0
RM    -1.114746e-15  1.0
AGE   -1.114746e-15  1.0
DIS   -1.114746e-15  1.0
RAD   -1.114746e-15  1.0
TAX   -1.114746e-15  1.0

In [15]:
# NORMALIZER
# Normalize samples individually to unit norm.
# Each sample (i.e. each row of the data matrix) with at least one non zero component is rescaled independently of other samples so that its norm (l1 or l2) equals one.
# Scaling inputs to unit norms is a common operation for text classification or clustering for instance
from sklearn.preprocessing import Normalizer #import appropriate library
transformer = Normalizer().fit(Class1_X) # fit does nothing
print(transformer)
normalised = transformer.transform(Class1_X)
print(normalised)
mean_std_transformed = pd.DataFrame(data={'mean':normalised.mean(), 'std':normalised.std()}, index=Class1_X.columns) #have another look at the transformed data
mean_std_transformed[0:10] # call the dataframe

Normalizer(copy=True, norm='l2')
[[1.26388341e-05 3.59966795e-02 4.61957387e-03 ... 3.05971776e-02
  7.93726783e-01 9.95908132e-03]
 [5.78529889e-05 0.00000000e+00 1.49769546e-02 ... 3.77071843e-02
  8.40785474e-01 1.93620036e-02]
 [5.85729947e-05 0.00000000e+00 1.51744622e-02 ... 3.82044450e-02
  8.43137761e-01 8.64965806e-03]
 ...
 [1.23765824e-04 0.00000000e+00 2.43009593e-02 ... 4.27762066e-02
  8.08470305e-01 1.14884669e-02]
 [2.24644719e-04 0.00000000e+00 2.44548909e-02 ... 4.30471676e-02
  8.06519433e-01 1.32831260e-02]
 [9.69214289e-05 0.00000000e+00 2.43887924e-02 ... 4.29308164e-02
  8.11392431e-01 1.61092778e-02]]


mean       std
CRIM   0.123567  0.248303
ZN     0.123567  0.248303
INDUS  0.123567  0.248303
CHAS   0.123567  0.248303
NOX    0.123567  0.248303
RM     0.123567  0.248303
AGE    0.123567  0.248303
DIS    0.123567  0.248303
RAD    0.123567  0.248303
TAX    0.123567  0.248303

In [16]:
#Model Evaluation and Metrics
#testing and training splits
from sklearn.model_selection import train_test_split
# splits data into a test and training set
# function shuffles our data before splitting (we will get both classes in both sets)
# setting a random_state means that this shuffling will be consistent for each run
#setting stratify=class_y tells the function to have an even number of class labels in each set
X_train, X_test, y_train, y_test = train_test_split(class_X,class_y, test_size=0.3, random_state=1, stratify = class_y)

# verify the stratifications using np.bincount
print('Labels counts in y:', np.bincount(class_y))
print('Percentage of class zeroes in class_y',np.round(np.bincount(class_y)[0]/len(class_y)*100))

print("\n")
print('Labels counts in y_train:', np.bincount(y_train))
print('Percentage of class zeroes in y_train',np.round(np.bincount(y_train)[0]/len(y_train)*100))

print("\n")
print('Labels counts in y_test:', np.bincount(y_test))
print('Percentage of class zeroes in y_test',np.round(np.bincount(y_test)[0]/len(y_test)*100))

Labels counts in y: [212 357]
Percentage of class zeroes in class_y 37.0


Labels counts in y_train: [148 250]
Percentage of class zeroes in y_train 37.0


Labels counts in y_test: [ 64 107]
Percentage of class zeroes in y_test 37.0


Additional ways to divide data into test and training sets exist, and we cover K-fold cross validation in the Pipeline section

In [17]:
#create a basiline model to benchmark our other estimators against
#this can be simple estimator or we can use a dummy estimator to make predictions in a random manner
#import appropriate statement
from sklearn.dummy import DummyClassifier
# creates our dummy classifier and the value we pass in to the strategy
dummy = DummyClassifier(strategy='uniform', random_state=1)
dummy.fit(X_train,y_train) # #train the model

DummyClassifier(constant=None, random_state=1, strategy='uniform')

In [18]:
#evaluate model metrics
dummy.score(X_test, y_test) # get an accuracy score

0.47953216374269003

Remember that to get a score, we need to instantiate a model, fit it to the data, predict using unseen data, compare the predictions against actual data, and score the difference. This is true for classification and regression problems, and is true no matter the method used to get there.

* So, in the end-to-end tutorials we split the training and test data, fitted our data to an estimator, and called the .predict method on the estimator to get our predictions, and then passed this to a scoring function (four steps)
* In using the estimator.score() method above, we are passing in our split data and the method is then making predictions and returning the score (three steps).
* In the cross_val_score() method used below we are effectively using one step as the method takes an estimator and our data and returns a score.

In [19]:
#fit a new estimator and use cross_val_score to get a score based defined metric
#import statements
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression() # instantiate logistic regression classifier

#pass estimator and data to the method. also specify the number of folds (default is 3)
# the default scoring method is associated with the estimator we pass in
# use scoring parameter to pass in different scoring methods. here we use recall
cross_val_score(logistic, class_X, class_y, cv=5, scoring="recall")

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur

array([0.98611111, 0.97222222, 0.98591549, 0.95774648, 0.95774648])

In [20]:
#Excercise 3

#Part 1 -Implement binary classification scoring functions

#Implement f1 score - also known as balanced F-score or F-measure
# F1 score can be interpreted as a weighted average of the precision and recall, where an F1 score reaches its best value at 1 and worst score at 0. The relative contribution of precision and recall to the F1 score are equal. The formula for the F1 score is:
# F1 = 2 * (precision * recall) / (precision + recall) 
#import appropriate statements
from sklearn.metrics import f1_score

f1 = cross_val_score(logistic, class_X, class_y, cv=5, scoring='f1') 
print('f1')
print(f1)
f1macro = cross_val_score(logistic, class_X, class_y, cv=5, scoring='f1_macro') #Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.
print('f1macro')
print(f1macro)
f1micro = cross_val_score(logistic, class_X, class_y, cv=5, scoring='f1_micro') #Calculate metrics globally by counting the total true positives, false negatives and false positives.
print('f1micro')
print(f1micro)
f1weighted = cross_val_score(logistic, class_X, class_y, cv=5, scoring='f1_weighted') #Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label). This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.
print('f1weighted')
print(f1weighted)


##implement precision score
#The precision is the ratio tp / (tp + fp) where tp is the number of true positives and fp the number of false positives. The precision is intuitively the ability of the classifier not to label as positive a sample that is negative.
#The best value is 1 and the worst value is 0.
#import appropriate statements
from sklearn.metrics import precision_score
precision = cross_val_score(logistic, class_X, class_y, cv=5, scoring='precision') 
print('precision')
print(precision)
precisionmacro = cross_val_score(logistic, class_X, class_y, cv=5, scoring='precision_macro') #Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account
print('precisionmacro')
print(precisionmacro)
precisionmicro = cross_val_score(logistic, class_X, class_y, cv=5, scoring='precision_micro') #Calculate metrics globally by counting the total true positives, false negatives and false positives.
print('precisionmicro')
print(precisionmicro)
precisionweighted = cross_val_score(logistic, class_X, class_y, cv=5, scoring='precision_weighted') #Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label). This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.
print('precisionweighted')
print(precisionweighted)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur

f1
[0.94666667 0.95238095 0.97902098 0.96453901 0.97142857]
f1macro
[0.92333333 0.9340218  0.9714382  0.95285774 0.96245847]
f1micro
[0.93043478 0.93913043 0.97345133 0.95575221 0.96460177]
f1weighted
[0.92921739 0.9386515  0.97338422 0.95585559 0.96476053]
precision
[0.91025641 0.93333333 0.97222222 0.97142857 0.98550725]
precisionmacro
[0.94161469 0.94166667 0.97391599 0.95083056 0.95866271]
precisionmicro
[0.93043478 0.93913043 0.97345133 0.95575221 0.96460177]
precisionweighted
[0.93370695 0.93956522 0.97348131 0.95611678 0.96555202]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  Futur

In [0]:
# Part 2
#Assessing our model's performance with the Receiving Operating Characteristic (ROC) Curve.

A useful tool when predicting the probability of a binary outcome is the Receiver Operating Characteristic curve, or ROC curve. 
It is a plot of the false positive rate (x-axis) versus the true positive rate (y-axis) for a number of different candidate threshold values between 0.0 and 1.0. Put another way, it plots the false alarm rate versus the hit rate.

The true positive rate is calculated as the number of true positives divided by the sum of the number of true positives and the number of false negatives. It describes how good the model is at predicting the positive class when the actual outcome is positive.


* *True Positive Rate* = True Positives / (True Positives + False Negatives)

The true positive rate is also referred to as sensitivity.

* *Sensitivity* = True Positives / (True Positives + False Negatives)

The false positive rate is calculated as the number of false positives divided by the sum of the number of false positives and the number of true negatives. It is also called the false alarm rate as it summarizes how often a positive class is predicted when the actual outcome is negative.

* False Positive Rate = False Positives / (False Positives + True Negatives)

The false positive rate is also referred to as the inverted specificity where specificity is the total number of true negatives divided by the sum of the number of true negatives and false positives.

* Specificity = True Negatives / (True Negatives + False Positives)  
Where:            False Positive Rate = 1 - Specificity
      
The ROC curve is a useful tool for a few reasons:
* The curves of different models can be compared directly in general or for different thresholds.
* The area under the curve (AUC) can be used as a summary of the model skill.
The shape of the curve contains a lot of information, including what we might care about most for a problem, the expected false positive rate, and the false negative rate. To make this clear: a. Smaller values on the x-axis of the plot indicate lower false positives and higher true negatives. b. Larger values on the y-axis of the plot indicate higher true positives and lower false negatives.

In [0]:
# import roc_curve() to plot a ROC curve. 
# The function takes both the true outcomes (0,1) from the test set and the predicted probabilities for the 1 class. The function returns the false positive rates for each threshold, true positive rates for each threshold and thresholds.
from sklearn.metrics import roc_curve 
# import roc_auc_score() to calculate AUC for ROC
# AUC function takes both the true outcomes (0,1) from the test set and the predicted probabilities for the 1 class. It returns the AUC score between 0.0 and 1.0 for no skill and perfect skill respectively.
from sklearn.metrics import roc_auc_score 
import matplotlib.pyplot as plt 
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()
#from sklearn import svm # import svm for classification
fpr, tpr, thresholds = roc_curve(class_y, f1, pos_label=2)