<a href="https://colab.research.google.com/github/anjali88/Basic-ML-/blob/master/Pushpanjali_banik_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Excercise 1 - Demo difference between numpy and python
#import numpy
import numpy as np
my_arr = np.arange(1000000) # create numpy array
my_list = list(range(1000000)) #create python list with same values but it is not stored as numpy array

# computationl time in numpy
%time my_arr2 = my_arr * 2

CPU times: user 2.03 ms, sys: 6.45 ms, total: 8.49 ms
Wall time: 8.28 ms


In [5]:
# computationl time in python
%time my_list2 = [x *2 for x in my_list]

CPU times: user 58.5 ms, sys: 56.2 ms, total: 115 ms
Wall time: 119 ms


In [6]:
# Excercise 2.1 - Creating arrays
# create an array by passin in values
a = np.array([0,2,4])
a

array([0, 2, 4])

In [7]:
#create 2D array
b = np.array([[0,2,4], [1,3,5]])
b

array([[0, 2, 4],
       [1, 3, 5]])

In [8]:
#create an array of all zeros, with three rows of three column each
c = np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#create a 2x2 constant array
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [16]:
#create a 3x3 constant array
e = np.full((3,3), 6)
e


array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [17]:
#create a 4x3 array filled with random values
f = np.random.random((4,3))
f

array([[0.88481858, 0.33058435, 0.99819552],
       [0.44153579, 0.76130142, 0.89379922],
       [0.92501178, 0.45491338, 0.04411624],
       [0.55501406, 0.30195189, 0.10015048]])

In [18]:
#creare a 3x3matrix with ones on the diagonal
#np.identity also serves same purpose
g = np.eye(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
g = np.identity(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#convert list to array
h = list((2, 3, 4, 1))
n = np.array(h)
h

[2, 3, 4, 1]

In [22]:
#arange() will create arrays with regulary incrementing values
i = np.arange(10)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#linespace () creates arrays with a specified nu,ber of items which are spaced equally between the specified begining and ending values
j = np.linspace(1., 3., 6)
j 

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [26]:
#Excercise 2.1 
# create array using np.arange() and add start, stop and step parameters
#add numpy.arange([start, ]stop, [step, ]dtype=None))
# start = number, optinal. Start of interval. Default value is 0
#Stop = number, End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.
#Step = number, optional. Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.
np.arange (15, 25, 2) # start value is 15 , stop value is 25 and 2 is the step value adjacent numbers


array([15, 17, 19, 21, 23])

In [27]:
#Excercise 2.2 -Accessing arrays
print("1D array:\n", a)

1D array:
 [0 2 4]


In [28]:
#access the shape of the array
print("\nDimensions of array:", a.shape)


Dimensions of array: (3,)


In [0]:
#call the individual elements of the array using the elements index