<a href="https://colab.research.google.com/github/anjali88/Basic-ML-/blob/master/Pushpanjali_Banik_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Excercise 1 - Demo difference between numpy and python
#import numpy
import numpy as np
my_arr = np.arange(1000000) # create numpy array
my_list = list(range(1000000)) #create python list with same values but it is not stored as numpy array

# computationl time in numpy
%time my_arr2 = my_arr * 2

CPU times: user 2.03 ms, sys: 6.45 ms, total: 8.49 ms
Wall time: 8.28 ms


In [5]:
# computationl time in python
%time my_list2 = [x *2 for x in my_list]

CPU times: user 58.5 ms, sys: 56.2 ms, total: 115 ms
Wall time: 119 ms


In [6]:
# Excercise 2.1 - Creating arrays
# create an array by passin in values
a = np.array([0,2,4])
a

array([0, 2, 4])

In [7]:
#create 2D array
b = np.array([[0,2,4], [1,3,5]])
b

array([[0, 2, 4],
       [1, 3, 5]])

In [8]:
#create an array of all zeros, with three rows of three column each
c = np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#create a 2x2 constant array
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [16]:
#create a 3x3 constant array
e = np.full((3,3), 6)
e


array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [17]:
#create a 4x3 array filled with random values
f = np.random.random((4,3))
f

array([[0.88481858, 0.33058435, 0.99819552],
       [0.44153579, 0.76130142, 0.89379922],
       [0.92501178, 0.45491338, 0.04411624],
       [0.55501406, 0.30195189, 0.10015048]])

In [18]:
#creare a 3x3matrix with ones on the diagonal
#np.identity also serves same purpose
g = np.eye(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
g = np.identity(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#convert list to array
h = list((2, 3, 4, 1))
n = np.array(h)
h

[2, 3, 4, 1]

In [22]:
#arange() will create arrays with regulary incrementing values
i = np.arange(10)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#linespace () creates arrays with a specified number of items which are spaced equally between the specified begining and ending values
j = np.linspace(1., 3., 6)
j 

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [26]:
#Excercise 2.1 
# create array using np.arange() and add start, stop and step parameters
#add numpy.arange([start, ]stop, [step, ]dtype=None))
# start = number, optinal. Start of interval. Default value is 0
#Stop = number, End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.
#Step = number, optional. Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.
np.arange (15, 25, 2) # start value is 15 , stop value is 25 and 2 is the step value adjacent numbers


array([15, 17, 19, 21, 23])

In [27]:
#Excercise 2.2 -Accessing arrays
print("1D array:\n", a)

1D array:
 [0 2 4]


In [28]:
#access the shape of the array
print("\nDimensions of array:", a.shape)


Dimensions of array: (3,)


In [29]:
#call the individual elements of the array using the elements index
print("\nFirst element of array: ", a[0])
print("\nSecond element of array", a[1])
print("\nThird element of array:", a[2])



First element of array:  0

Second element of array 2

Third element of array: 4


In [34]:
#compare this to a 2D array
print("2D array: \n", b)


2D array: 
 [[0 2 4]
 [1 3 5]]


In [31]:
#contrast the shape of this array with the shape of 'a'
print("\nDimensions of 2D array:", b.shape)


Dimensions of 2D array: (2, 3)


In [35]:
#understand how values are accessed
print("\nArray element [0,0]:", b[0, 0])
print("\nArray elements [1,2] [0,1] [1,0]:", b[1,2], b[0,1], b[1,0])


Array element [0,0]: 0

Array elements [1,2] [0,1] [1,0]: 5 2 1


In [36]:
#create array and access the first two elements
k =np.array([4,6,8,10])
k[0:2]

array([4, 6])

In [48]:
#Array slicing
print("\n2D array a:", a)
print("\nRow 1 second element of a:", a[1:2]) # print row 1 second element
print(" \nlast 2 elements of a:", a[-2:]) #  print last 2 elements
print("\neverything except last 2 elements of a:", a[:-2]) # print everything except last 2 elements


2D array a: [0 2 4]

Row 1 second element of a: [2]
 
last 2 elements of a: [2 4]

everything except last 2 elements of a: [0]


In [50]:
#high dimension slicing
l = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(l)
l[2] # access one row of array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [39]:
#access values within one row 
l[2, :2]

array([7, 8])

In [40]:
# or use this command
l[2][:2]

array([7, 8])

In [41]:
#access all rows (axis 0) and two columns (axis 1)
l[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [51]:
#Accessing arrays
#create 2D array
# EXERCISE CODE HERE
Y = np.random.random((2,3)) #Random value 2D array
Y

array([[0.41275367, 0.3151473 , 0.10293633],
       [0.18488648, 0.03826079, 0.37294377]])

In [52]:
#create 2D array containing slice of Y
X = np.array([[1,2,Y[1,0]],[3,5,6]])
X

array([[1.        , 2.        , 0.18488648],
       [3.        , 5.        , 6.        ]])

In [53]:
#create variable containing slice of X
array_slice = X[1,2]
array_slice

6.0

In [54]:
#Replace value of sliced array
array_slice = 0
# Notice if array X is changed 
X

array([[1.        , 2.        , 0.18488648],
       [3.        , 5.        , 6.        ]])

The value of 2D array X remains unchanged