<a href="https://colab.research.google.com/github/anjali88/Basic-ML-/blob/master/Pushpanjali_Banik_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Excercise 1 - Demo difference between numpy and python
#import numpy
import numpy as np
my_arr = np.arange(1000000) # create numpy array
my_list = list(range(1000000)) #create python list with same values but it is not stored as numpy array

# computationl time in numpy
%time my_arr2 = my_arr * 2

CPU times: user 1.44 ms, sys: 4.1 ms, total: 5.54 ms
Wall time: 10.5 ms


In [0]:
# computationl time in python
%time my_list2 = [x *2 for x in my_list]

CPU times: user 58.5 ms, sys: 56.2 ms, total: 115 ms
Wall time: 119 ms


In [0]:
# Excercise 2.1 - Creating arrays
# create an array by passin in values
a = np.array([0,2,4])
a

array([0, 2, 4])

In [0]:
#create 2D array
b = np.array([[0,2,4], [1,3,5]])
b

array([[0, 2, 4],
       [1, 3, 5]])

In [0]:
#create an array of all zeros, with three rows of three column each
c = np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
#create a 2x2 constant array
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [0]:
#create a 3x3 constant array
e = np.full((3,3), 6)
e


array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [0]:
#create a 4x3 array filled with random values
f = np.random.random((4,3))
f

array([[0.88481858, 0.33058435, 0.99819552],
       [0.44153579, 0.76130142, 0.89379922],
       [0.92501178, 0.45491338, 0.04411624],
       [0.55501406, 0.30195189, 0.10015048]])

In [0]:
#creare a 3x3matrix with ones on the diagonal
#np.identity also serves same purpose
g = np.eye(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
g = np.identity(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
#convert list to array
h = list((2, 3, 4, 1))
n = np.array(h)
h

[2, 3, 4, 1]

In [0]:
#arange() will create arrays with regulary incrementing values
i = np.arange(10)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#linespace () creates arrays with a specified number of items which are spaced equally between the specified begining and ending values
j = np.linspace(1., 3., 6)
j 

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [0]:
#Excercise 2.1 
# create array using np.arange() and add start, stop and step parameters
#add numpy.arange([start, ]stop, [step, ]dtype=None))
# start = number, optinal. Start of interval. Default value is 0
#Stop = number, End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.
#Step = number, optional. Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.
np.arange (15, 25, 2) # start value is 15 , stop value is 25 and 2 is the step value adjacent numbers


array([15, 17, 19, 21, 23])

In [0]:
#Excercise 2.2 -Accessing arrays
print("1D array:\n", a)

1D array:
 [0 2 4]


In [0]:
#access the shape of the array
print("\nDimensions of array:", a.shape)


Dimensions of array: (3,)


In [0]:
#call the individual elements of the array using the elements index
print("\nFirst element of array: ", a[0])
print("\nSecond element of array", a[1])
print("\nThird element of array:", a[2])


First element of array:  0

Second element of array 2

Third element of array: 4


In [0]:
#compare this to a 2D array
print("2D array: \n", b)

2D array: 
 [[0 2 4]
 [1 3 5]]


In [0]:
#contrast the shape of this array with the shape of 'a'
print("\nDimensions of 2D array:", b.shape)


Dimensions of 2D array: (2, 3)


In [0]:
#understand how values are accessed
print("\nArray element [0,0]:", b[0, 0])
print("\nArray elements [1,2] [0,1] [1,0]:", b[1,2], b[0,1], b[1,0])


Array element [0,0]: 0

Array elements [1,2] [0,1] [1,0]: 5 2 1


In [0]:
#create array and access the first two elements
k =np.array([4,6,8,10])
k[0:2]

array([4, 6])

In [0]:
#Array slicing
print("\n2D array a:", a)
print("\nRow 1 second element of a:", a[1:2]) # print row 1 second element
print(" \nlast 2 elements of a:", a[-2:]) #  print last 2 elements
print("\neverything except last 2 elements of a:", a[:-2]) # print everything except last 2 elements


2D array a: [0 2 4]

Row 1 second element of a: [2]
 
last 2 elements of a: [2 4]

everything except last 2 elements of a: [0]


In [0]:
#high dimension slicing
l = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(l)
l[2] # access one row of array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [0]:
#access values within one row 
l[2, :2]

array([7, 8])

In [0]:
# or use this command
l[2][:2]

array([7, 8])

In [0]:
#access all rows (axis 0) and two columns (axis 1)
l[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [0]:
#Excercise 2.1 - Accessing arrays
#create 2D array
Y = np.random.random((2,3)) #Random value 2D array
Y

array([[0.41275367, 0.3151473 , 0.10293633],
       [0.18488648, 0.03826079, 0.37294377]])

In [0]:
#create 2D array containing slice of Y
X = np.array([[1,2,Y[1,0]],[3,5,6]])
X

array([[1.        , 2.        , 0.18488648],
       [3.        , 5.        , 6.        ]])

In [0]:
#create variable containing slice of X
array_slice = X[1,2]
array_slice

6.0

In [0]:
#Replace value of sliced array
array_slice = 0
# Notice if array X is changed 
X

array([[1.        , 2.        , 0.18488648],
       [3.        , 5.        , 6.        ]])

The value of 2D array X remains unchanged

In [0]:
#Excercise 2.3 - Properties of arrays
#change an element of the array inplace
print("X before changing an element value in place:\n", X)
#change the value at first elements
X[0] = 10
print("\nX after changing an element value in place:\n",X)

X before changing an element value in place:
 [[1.         2.         0.18488648]
 [3.         5.         6.        ]]

X after changing an element value in place:
 [[10. 10. 10.]
 [ 3.  5.  6.]]


In [0]:
#access the data type of an array using '.dtype'
print("Data type of X:", X.dtype)

Data type of X: float64


In [0]:
#numpy automatically assigned us the data type - but we can specify it
X_float = np.array(X, dtype=np.float64)
print(X_float.dtype)
X_float # see that the array has a decimal point after the number 

float64


array([[10., 10., 10.],
       [ 3.,  5.,  6.]])

In [0]:
#convert or cast an array from one dtyoe to another using ndarrays astype method
X_int32 = X_float.astype(np.int32)
print(X_int32.dtype)
X_int32 # notice that numbers converted to integers 

int32


array([[10, 10, 10],
       [ 3,  5,  6]], dtype=int32)

In [0]:
#convert from strings to numbers 
numeric_strings = np.array(['1.5', '-10', '30'], dtype=np.string_)
numeric_strings.astype(float) # use float or np.float

array([  1.5, -10. ,  30. ])

In [0]:
#. reshape attribute 
print(X)
print(X.shape)

#reshape, note the new shape must fit the same number of values
Z = X.reshape(3,2)
Z

[[10. 10. 10.]
 [ 3.  5.  6.]]
(2, 3)


array([[10., 10.],
       [10.,  3.],
       [ 5.,  6.]])

In [0]:
#passing -1 as second parameter means numpy will infer the size of the second value
#use incase of large array
N =np.arange(1200).reshape(2,-1)
print(N.shape)
print(N)

(2, 600)
[[   0    1    2 ...  597  598  599]
 [ 600  601  602 ... 1197 1198 1199]]


In [0]:
#join two different arrays either vertically (axis 0) or horizontally (axis 1)
E = np.array([np.arange(0,3),np.arange(2,5),np.arange(5,8)])
print("\nArray E:\n", E)
F = np.random.random((3,3))
print("\nArray F:\n", F)
J = np.vstack((E,F)) # join - stack arrays verticaly, it takes a tuple as an argument
print("\nArray J:\n", J)
C = np.hstack((E,F))# join - stack arrays horizontaly
print("\nArray C:\n", C)


Array E:
 [[0 1 2]
 [2 3 4]
 [5 6 7]]

Array F:
 [[0.652069   0.26350407 0.416652  ]
 [0.72467533 0.07135996 0.83366769]
 [0.47513434 0.65407597 0.69879294]]

Array J:
 [[0.         1.         2.        ]
 [2.         3.         4.        ]
 [5.         6.         7.        ]
 [0.652069   0.26350407 0.416652  ]
 [0.72467533 0.07135996 0.83366769]
 [0.47513434 0.65407597 0.69879294]]

Array C:
 [[0.         1.         2.         0.652069   0.26350407 0.416652  ]
 [2.         3.         4.         0.72467533 0.07135996 0.83366769]
 [5.         6.         7.         0.47513434 0.65407597 0.69879294]]


In [0]:
#use .ravel() or .flatten to return to 1D array
q = J.ravel()
print("\nArray q:\n",q)
r = C.flatten() # flatten returns a copy of the array, ravel does not - otherwise they perform the same
print("\nArray r:\n",r)


Array q:
 [0.         1.         2.         2.         3.         4.
 5.         6.         7.         0.652069   0.26350407 0.416652
 0.72467533 0.07135996 0.83366769 0.47513434 0.65407597 0.69879294]

Array r:
 [0.         1.         2.         0.652069   0.26350407 0.416652
 2.         3.         4.         0.72467533 0.07135996 0.83366769
 5.         6.         7.         0.47513434 0.65407597 0.69879294]


In [0]:
#Excercise 2.3 - Array properties
G = np.array([np.arange(0,3),np.arange(2,5)]) #2D array
print("\nArray G:\n", G)
G1 = G.reshape(3,2) # reshape 
print("\nArray G1:\n", G1)
F1 = np.random.random((3,2))# random value 2D array
print("\nArray F1:\n", F1)
J1 = np.vstack((G1,F1)) # join - stack arrays verticaly
print("\nArray J1:\n", J1)
C1 = np.hstack((G1,F1))# join - stack arrays horizontaly
print("\nArray C1:\n", C1)
q1 = J1.ravel() # convert to 1D array
print("\nArray q1:\n",q1)
r1 = C1.flatten() # flatten returns a copy of the array
print("\nArray r1:\n",r1)


Array G:
 [[0 1 2]
 [2 3 4]]

Array G1:
 [[0 1]
 [2 2]
 [3 4]]

Array F1:
 [[0.63840772 0.70841107]
 [0.75593712 0.070072  ]
 [0.98226748 0.44278496]]

Array J1:
 [[0.         1.        ]
 [2.         2.        ]
 [3.         4.        ]
 [0.63840772 0.70841107]
 [0.75593712 0.070072  ]
 [0.98226748 0.44278496]]

Array C1:
 [[0.         1.         0.63840772 0.70841107]
 [2.         2.         0.75593712 0.070072  ]
 [3.         4.         0.98226748 0.44278496]]

Array q1:
 [0.         1.         2.         2.         3.         4.
 0.63840772 0.70841107 0.75593712 0.070072   0.98226748 0.44278496]

Array r1:
 [0.         1.         0.63840772 0.70841107 2.         2.
 0.75593712 0.070072   3.         4.         0.98226748 0.44278496]


In [0]:
#Excercise 3- operations on Arrays
# arithmetic operations between equal-size arrays applies the operation element-wise:
q1 + r1

array([0.        , 2.        , 2.63840772, 2.70841107, 5.        ,
       6.        , 1.39434484, 0.77848308, 3.75593712, 4.070072  ,
       1.96453497, 0.88556992])

In [0]:
#universal functios (ufuncs), a function that a function that performs element-wise operations on data in ndarrays
np.add(G1,F1)

array([[0.63840772, 1.70841107],
       [2.75593712, 2.070072  ],
       [3.98226748, 4.44278496]])

In [0]:
# other arithmetic functions
G1 * F1

array([[0.        , 0.70841107],
       [1.51187425, 0.14014401],
       [2.94680245, 1.77113984]])

In [0]:
#with the ufunc equivalent
np.multiply(q1,r1)

array([0.        , 1.        , 1.27681544, 1.41682215, 6.        ,
       8.        , 0.4825961 , 0.04963978, 2.26781137, 0.28028801,
       0.96484941, 0.19605852])

In [0]:
#division 
1/a

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf, 0.5 , 0.25])

In [0]:
# raising a to the power 0.75
a **0.75

array([0.        , 1.68179283, 2.82842712])

In [0]:
#exponential -calculates calculates e raise x for each x in your list where e is Euler's number for each x in your list where e is Euler's number
np.exp(a)

array([ 1.        ,  7.3890561 , 54.59815003])

In [0]:
np.sqrt(a)# elementwise square root

array([0.        , 1.41421356, 2.        ])

In [0]:
#create two arrays
t = np.random.randn(8)
print(t)
w = np.random.randn(8)
print(w)
np.maximum(t, w) #compares the arrays

[ 1.58152579 -0.58872895 -2.07046962 -0.71883395  1.10463582  0.58242986
  0.60900024 -0.09867074]
[-0.42939258  0.90881791  0.58666218 -0.33366714 -0.61199956  0.0462085
 -2.02062189 -0.37046629]


array([ 1.58152579,  0.90881791,  0.58666218, -0.33366714,  1.10463582,
        0.58242986,  0.60900024, -0.09867074])

In [0]:
#statistical methods are available, such as mean(), sum() and cumsum() - cumulative sum()
np.sum(q1)

15.597880367440771

In [0]:
np.mean(q1)

1.2998233639533976

In [0]:
np.cumsum(q1)

array([ 0.        ,  1.        ,  3.        ,  5.        ,  8.        ,
       12.        , 12.63840772, 13.3468188 , 14.10275592, 14.17282792,
       15.15509541, 15.59788037])

In [0]:
# we can use boolean operations to filter values
u = np.array([[1,2], [3,4], [5,6]]) 
print(u)
#find the element in u that are bigger than 2
print((u>2))

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [0]:
#use mask to get actual value
print("Values of array elements bigger than 2")
print(u[u > 2])

Values of array elements bigger than 2
[3 4 5 6]


In [67]:
#Excercise 3.1
#create two arrays
t1 = np.random.random(4)
print(t1)
w1 = np.arange(4)
print(w1)
N1 = (np.multiply(t1,w1))/2
print(N1)
N2 = np.mean(N1)
print(N2)
N1[1:3]

[0.15822365 0.93713675 0.55009296 0.62910561]
[0 1 2 3]
[0.         0.46856837 0.55009296 0.94365841]
0.49057993668291877


array([0.46856837, 0.55009296])